### get goals
GET https://jwt-auth-eight-neon.vercel.app/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM3LCJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImhlbGxvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzgzNzAxNTc3LCJleHAiOjE3ODM3ODc5Nzd9.FJNlRTWGwyCDwdKtKC9LeGXG8Xs6pHr0SQLWjxVhekU
Content-Type: application/json

### post goals
POST https://jwt-auth-eight-neon.vercel.app/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM3LCJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImhlbGxvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzgzNzAxNTc3LCJleHAiOjE3ODM3ODc5Nzd9.FJNlRTWGwyCDwdKtKC9LeGXG8Xs6pHr0SQLWjxVhekU
Content-Type: application/json

{
  "target_amount": 5000,
  "present_amount": 2100
}

